### PR TITLE
Added alternate locations for PWM.

### PR DESCRIPTION
**Pull request by marcuschangarm**
pwmout-api.c:
- Added support for alternate locations.
- Added wider range for setting pulsewidth using micro seconds.

### CODE REVIEW

**Comment by 0xc0170** [comment]
cc @stevew817 @akselsm

**Comment by stevew817** [comment]
@marcuschangarm pwmout_api has been rehauled as part of the Pearl Gecko port in our mbedv2 HAL, for which the pull request is now open (1501 on mbedmicro/mbed). The expectation is that once accepted, the same HAL changes will make it over into mbed-hal-silabs for mbedOS, so merging this now would not be very great timing.
However, it is a very good suggestion, and we will implement it on top of the new pwmout_api ASAP.

**Comment by marcuschangarm** [comment]
Sounds good.

While you are at it, I noticed the power consumption is in the mA range when pwm is enabled on the STK3700 even without anything connected. Could you please have a look at it when you get around to the pwm for mbed OS?

**Comment by stevew817** [comment]
mA range figure is correct. PWM relies on a TIMER peripheral, which in turn is driven off of a high speed clock, meaning the chip cannot sleep lower than EM1 with active PWM. This is why we implemented _free in the PWM update, so that the chip can go to a lower sleep mode again once all PWM objects are destroyed.

**Comment by marcuschangarm** [comment]
I see. Looking forward to see the update hitting mbed OS then! :)

**Pull request closed without merging**
